[2023-07-11T08:37:51.909+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: process_sales_4.extract_data_from_api manual__2023-07-11T08:37:49.649542+00:00 [queued]>
[2023-07-11T08:37:51.923+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: process_sales_4.extract_data_from_api manual__2023-07-11T08:37:49.649542+00:00 [queued]>
[2023-07-11T08:37:51.924+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-07-11T08:37:51.953+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): extract_data_from_api> on 2023-07-11 08:37:49.649542+00:00
[2023-07-11T08:37:51.960+0000] {standard_task_runner.py:57} INFO - Started process 1292 to run task
[2023-07-11T08:37:51.966+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'process_sales_4', 'extract_data_from_api', 'manual__2023-07-11T08:37:49.649542+00:00', '--job-id', '60', '--raw', '--subdir', 'DAGS_FOLDER/process_sales_4.py', '--cfg-path', '/tmp/tmp2x990z2z']
[2023-07-11T08:37:51.967+0000] {standard_task_runner.py:85} INFO - Job 60: Subtask extract_data_from_api
[2023-07-11T08:37:52.033+0000] {task_command.py:410} INFO - Running <TaskInstance: process_sales_4.extract_data_from_api manual__2023-07-11T08:37:49.649542+00:00 [running]> on host ca64464cba28
[2023-07-11T08:37:52.136+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='process_sales_4' AIRFLOW_CTX_TASK_ID='extract_data_from_api' AIRFLOW_CTX_EXECUTION_DATE='2023-07-11T08:37:49.649542+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-07-11T08:37:49.649542+00:00'
[2023-07-11T08:37:52.140+0000] {logging_mixin.py:149} INFO - 	I'm in get_sales(...) function!
[2023-07-11T08:37:52.383+0000] {logging_mixin.py:149} INFO - Page 1 started
[2023-07-11T08:37:52.387+0000] {logging_mixin.py:149} INFO - Page 1 done
[2023-07-11T08:37:52.387+0000] {logging_mixin.py:149} INFO - Status_code = 200
[2023-07-11T08:37:52.546+0000] {logging_mixin.py:149} INFO - Page 2 started
[2023-07-11T08:37:52.549+0000] {logging_mixin.py:149} INFO - Page 2 done
[2023-07-11T08:37:52.550+0000] {logging_mixin.py:149} INFO - Status_code = 200
[2023-07-11T08:37:52.708+0000] {logging_mixin.py:149} INFO - Page 3 started
[2023-07-11T08:37:52.712+0000] {logging_mixin.py:149} INFO - Page 3 done
[2023-07-11T08:37:52.713+0000] {logging_mixin.py:149} INFO - Status_code = 200
[2023-07-11T08:37:52.872+0000] {logging_mixin.py:149} INFO - Page 4 started
[2023-07-11T08:37:52.873+0000] {logging_mixin.py:149} INFO - Page 4 done
[2023-07-11T08:37:52.873+0000] {logging_mixin.py:149} INFO - Status_code = 200
[2023-07-11T08:37:53.039+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ht_template/job1/bll/sales_api.py", line 23, in save_sales_to_local_disk
    json_content.to_csv(f"{raw_dir}/{file_name}", index=False)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 3482, in to_csv
    storage_options=storage_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/formats/format.py", line 1105, in to_csv
    csv_formatter.save()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/formats/csvs.py", line 243, in save
    storage_options=self.storage_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/processed_data/raw/sales/2022-08-09/sales_2022-08-09.json'
[2023-07-11T08:37:53.057+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=process_sales_4, task_id=extract_data_from_api, execution_date=20230711T083749, start_date=20230711T083751, end_date=20230711T083753
[2023-07-11T08:37:53.072+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 60 for task extract_data_from_api ([Errno 2] No such file or directory: '/opt/airflow/processed_data/raw/sales/2022-08-09/sales_2022-08-09.json'; 1292)
[2023-07-11T08:37:53.099+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-11T08:37:53.118+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
