[2023-07-10T12:24:46.643+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: process_sales_2.extract_data_from_api manual__2023-07-10T09:42:31.548393+00:00 [queued]>
[2023-07-10T12:24:46.664+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: process_sales_2.extract_data_from_api manual__2023-07-10T09:42:31.548393+00:00 [queued]>
[2023-07-10T12:24:46.672+0000] {taskinstance.py:1308} INFO - Starting attempt 2 of 2
[2023-07-10T12:24:46.722+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): extract_data_from_api> on 2023-07-10 09:42:31.548393+00:00
[2023-07-10T12:24:46.731+0000] {standard_task_runner.py:57} INFO - Started process 61 to run task
[2023-07-10T12:24:46.738+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'process_sales_2', 'extract_data_from_api', 'manual__2023-07-10T09:42:31.548393+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/process_sales_2.py', '--cfg-path', '/tmp/tmpbccdpkea']
[2023-07-10T12:24:46.741+0000] {standard_task_runner.py:85} INFO - Job 36: Subtask extract_data_from_api
[2023-07-10T12:24:47.483+0000] {task_command.py:410} INFO - Running <TaskInstance: process_sales_2.extract_data_from_api manual__2023-07-10T09:42:31.548393+00:00 [running]> on host 5810e5da9f97
[2023-07-10T12:24:47.641+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='process_sales_2' AIRFLOW_CTX_TASK_ID='extract_data_from_api' AIRFLOW_CTX_EXECUTION_DATE='2023-07-10T09:42:31.548393+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-07-10T09:42:31.548393+00:00'
[2023-07-10T12:24:47.643+0000] {logging_mixin.py:149} INFO - 	I'm in get_sales(...) function!
[2023-07-10T12:24:49.580+0000] {logging_mixin.py:149} INFO - Page 1 started
[2023-07-10T12:24:49.582+0000] {logging_mixin.py:149} INFO - Page 1 done
[2023-07-10T12:24:49.582+0000] {logging_mixin.py:149} INFO - Status_code = 200
[2023-07-10T12:24:49.745+0000] {logging_mixin.py:149} INFO - Page 2 started
[2023-07-10T12:24:49.749+0000] {logging_mixin.py:149} INFO - Page 2 done
[2023-07-10T12:24:49.750+0000] {logging_mixin.py:149} INFO - Status_code = 200
[2023-07-10T12:24:49.909+0000] {logging_mixin.py:149} INFO - Page 3 started
[2023-07-10T12:24:49.912+0000] {logging_mixin.py:149} INFO - Page 3 done
[2023-07-10T12:24:49.913+0000] {logging_mixin.py:149} INFO - Status_code = 200
[2023-07-10T12:24:50.088+0000] {logging_mixin.py:149} INFO - Page 4 started
[2023-07-10T12:24:50.088+0000] {logging_mixin.py:149} INFO - Page 4 done
[2023-07-10T12:24:50.089+0000] {logging_mixin.py:149} INFO - Status_code = 200
[2023-07-10T12:24:50.248+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ht_template/job1/bll/sales_api.py", line 16, in save_sales_to_local_disk
    json_content.to_csv(f"{dag_path}/processed_data/{file_name}", index=False)
AttributeError: 'list' object has no attribute 'to_csv'
[2023-07-10T12:24:50.279+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=process_sales_2, task_id=extract_data_from_api, execution_date=20230710T094231, start_date=20230710T122446, end_date=20230710T122450
[2023-07-10T12:24:50.303+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 36 for task extract_data_from_api ('list' object has no attribute 'to_csv'; 61)
[2023-07-10T12:24:50.329+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-10T12:24:50.389+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
