[2023-07-10T12:28:02.437+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: process_sales_2.extract_data_from_api manual__2023-07-10T12:28:01.131283+00:00 [queued]>
[2023-07-10T12:28:02.445+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: process_sales_2.extract_data_from_api manual__2023-07-10T12:28:01.131283+00:00 [queued]>
[2023-07-10T12:28:02.446+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-07-10T12:28:02.461+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): extract_data_from_api> on 2023-07-10 12:28:01.131283+00:00
[2023-07-10T12:28:02.465+0000] {standard_task_runner.py:57} INFO - Started process 123 to run task
[2023-07-10T12:28:02.469+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'process_sales_2', 'extract_data_from_api', 'manual__2023-07-10T12:28:01.131283+00:00', '--job-id', '39', '--raw', '--subdir', 'DAGS_FOLDER/process_sales_2.py', '--cfg-path', '/tmp/tmpgpazb120']
[2023-07-10T12:28:02.472+0000] {standard_task_runner.py:85} INFO - Job 39: Subtask extract_data_from_api
[2023-07-10T12:28:02.518+0000] {task_command.py:410} INFO - Running <TaskInstance: process_sales_2.extract_data_from_api manual__2023-07-10T12:28:01.131283+00:00 [running]> on host 5810e5da9f97
[2023-07-10T12:28:02.591+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='process_sales_2' AIRFLOW_CTX_TASK_ID='extract_data_from_api' AIRFLOW_CTX_EXECUTION_DATE='2023-07-10T12:28:01.131283+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-07-10T12:28:01.131283+00:00'
[2023-07-10T12:28:02.593+0000] {logging_mixin.py:149} INFO - 	I'm in get_sales(...) function!
[2023-07-10T12:28:02.915+0000] {logging_mixin.py:149} INFO - Page 1 started
[2023-07-10T12:28:02.917+0000] {logging_mixin.py:149} INFO - Page 1 done
[2023-07-10T12:28:02.918+0000] {logging_mixin.py:149} INFO - Status_code = 200
[2023-07-10T12:28:03.079+0000] {logging_mixin.py:149} INFO - Page 2 started
[2023-07-10T12:28:03.083+0000] {logging_mixin.py:149} INFO - Page 2 done
[2023-07-10T12:28:03.084+0000] {logging_mixin.py:149} INFO - Status_code = 200
[2023-07-10T12:28:03.243+0000] {logging_mixin.py:149} INFO - Page 3 started
[2023-07-10T12:28:03.247+0000] {logging_mixin.py:149} INFO - Page 3 done
[2023-07-10T12:28:03.248+0000] {logging_mixin.py:149} INFO - Status_code = 200
[2023-07-10T12:28:03.407+0000] {logging_mixin.py:149} INFO - Page 4 started
[2023-07-10T12:28:03.408+0000] {logging_mixin.py:149} INFO - Page 4 done
[2023-07-10T12:28:03.408+0000] {logging_mixin.py:149} INFO - Status_code = 200
[2023-07-10T12:28:03.583+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ht_template/job1/bll/sales_api.py", line 16, in save_sales_to_local_disk
    json_content.to_csv(f"{dag_path}/processed_data/{file_name}", index=False)
AttributeError: 'list' object has no attribute 'to_csv'
[2023-07-10T12:28:03.601+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=process_sales_2, task_id=extract_data_from_api, execution_date=20230710T122801, start_date=20230710T122802, end_date=20230710T122803
[2023-07-10T12:28:03.613+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 39 for task extract_data_from_api ('list' object has no attribute 'to_csv'; 123)
[2023-07-10T12:28:03.648+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-10T12:28:03.674+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
